package: schemacategories
output: ../../../../generated/go/schema-categories/server.chi.gen.go
generate:
  models: true
  embedded-spec: true
  strict-server: true
  chi-server: true
output-options:
  skip-prune: true
import-mapping:
  ./common/pagination.yaml: "github.com/TCGLandDev/tcgdb/generated/go/common/pagination"
  ./common/iam.yaml: "github.com/TCGLandDev/tcgdb/generated/go/common/iam"
  ./common/problemdetails.yaml: "github.com/TCGLandDev/tcgdb/generated/go/common/problemdetails"
  ./common/primitives.yaml: "github.com/TCGLandDev/tcgdb/generated/go/common/primitives"
