package: users
output: ../../../../generated/go/users/handlers.chi.gen.go
generate:
  models: true
  embedded-spec: true
  strict-server: true
  chi-server: true
output-options:
  #  response-type-suffix: Response
  #  name-normalizer: ToCamelCaseWithDigits
  #  skip-fmt: false
  # Maybe useful in the future to split the generated code: https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#import-mapping
  # Donâ€™t reorder fields; helps smaller diffs
  skip-prune: true
#  leave-empty-json-tags: true # Keep JSON tags even if identical to field names (safer with mixed linters)
import-mapping:
  ./common/pagination.yaml: "github.com/zenGate-Global/palmyra-pro-saas/generated/go/common/pagination"
  ./common/iam.yaml: "github.com/zenGate-Global/palmyra-pro-saas/generated/go/common/iam"
  ./common/problemdetails.yaml: "github.com/zenGate-Global/palmyra-pro-saas/generated/go/common/problemdetails"
  ./common/primitives.yaml: "github.com/zenGate-Global/palmyra-pro-saas/generated/go/common/primitives"
